language: c

install:
  - sudo apt-get install luarocks
  - sudo luarocks install busted
  - sudo luarocks install 30log
  - sudo luarocks make rockspecs/largparse-lrcompat-1.rockspec

script: "busted spec"
